---
title: "Adult mosquito spatial and temporal distributions"
author: "Melissa DeSiervo"
date: "5/31/2020"
output: html_document
---


Install necessary packages
```{r Upload packages}
library(dplyr)
library(tidyr)
library(lme4)
library(ggplot2)
library(scales)
library(gridExtra)
library(reshape2)
library(emmeans) # v. 1.3.3
library(magrittr) # v. 1.5
library(lemon)
library(lubridate)
library(nlme)
library(MASS)
library(pscl)
library(here)
library(spatstat)

base_breaks <- function(n = 10){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}

```



```{r AIC function}


##aic function###
aictable<-function(X,m){
  #
  #  This function will create a full model selection table based on AICc.
  #  
  #  Inputs:
  #
  #  X is the AIC table produced by R by using AIC(model1,model2, ...)
  #  m is the sample size
  #
  #
  rnames<-row.names(X)
  AICc<-X$AIC+2*X$df*(X$df+1)/(m-X$df-1)     #small-sample correction
  logL<-X$df-X$AIC/2                         #Log-likelihood
  tab<-data.frame(X[,1],logL,AICc)           #Remove AIC column; add logL and AICc
  colnames(tab)[1]<-c("Params")              #Rename "df" column   
  row.names(tab)<-rnames
  tab<-tab[order(tab$AICc),]                 #Sort by ascending AICc value
  deltaAICc<-tab$AICc-min(tab$AICc)          #Delta AICc
  weight<-exp(-deltaAICc/2)/sum(exp(-deltaAICc/2))  #Weights
  cumwt<-weight                              #Column for cumulative weight
  for(i in 2:dim(X)[1]){                  
    cumwt[i]<-cumwt[i-1]+cumwt[i]              #Accumulate weight from the top
  }
  tab<-data.frame(tab,deltaAICc,weight,cumwt)
  tab<-round(tab,4)
  tab
}


```


```{r upload emergence trap data 2018}

emergencetraps <- read.csv(here("data/emergence_number_2018.csv"))

emergencetraps$Start.date <- as.Date(emergencetraps$Start.date, "%m/%d/%Y")
emergencetraps$Date.collected <- as.Date(emergencetraps$Date.collected, "%m/%d/%Y")

emergencetraps<-emergencetraps %>% mutate(Sitecode=Pond.1)



```


```{r Upload CO2 data 2017 2018 and fix date formats}

##c02 counts##

CO2counts20172018 <- read.csv(here("data/C02counts20172018.csv"))


CO2counts20172018$Year <- as.factor(CO2counts20172018$Year)
CO2counts20172018$Date<-as.Date(CO2counts20172018$Date, format = "%m/%d/%Y") 
CO2counts20172018$Date2<-as.Date(CO2counts20172018$Date2, format = "%m/%d/%Y") 


C02sitechar <- read.csv(here("data/C02sitechar.csv"))

C02sitechar$Site2 <- as.factor(C02sitechar$Site2)

#### subset out Golf and Kforest because of potential faulty trap issues###


CO2counts20172018subset<-CO2counts20172018 %>%   filter(SiteYear!= "Golf2018") %>%   filter(SiteYear!= "Forest2018")


levels(CO2counts20172018subset$Site)


CO2counts20172018subset<- CO2counts20172018subset %>% mutate(Sitecode=Site)

CO2counts20172018subset$Sitecode<-plyr::mapvalues(CO2counts20172018subset$Sitecode, c("Airport", "Bunny", "Camp", "Dispersal", "East", "Forest", "Golf", "KISS", "Moz valley", "Oil", "Seatomato", "Vulgaris", "VV2", "Waterfall", "Waterfall up"), c("F1a", "F3b", "F2a", "F3a", "1", "F1c", "1c", "F1b", "F3c", "1b", "F2b", "3", "F3d", "2a", "F2c"))

```


```{r upload sweep net data 2018}
##Sweep net 2018## ##from each sweep individual##


sweep2018<- read.csv(here("data/Sweep2018.csv"))


sweep2018$Date<-as.Date(sweep2018$Date, format = "%m/%d/%Y") 

sweep2018_2<-sweep2018%>% mutate(Jdate=yday(sweep2018$Date))

sweep2018$Sample<-as.factor(sweep2018$Sample)
sweep2018$Site2<-as.factor(sweep2018$Site2)


sweep2018<- sweep2018 %>% mutate(Sitecode=Pond)

sweep2018$Sitecode<-plyr::mapvalues(sweep2018$Sitecode, c("East", "Golf", "Ice", "NoOil", "Oil", "Vulgaris", "Vulgarissmall", "Waterfall"), c("1", "1c", "4", "1a", "1b", "3", "3a", "2a"))



```



```{r emergence traps totals by site}

##data cleaning###

#make the NAs be the average by date##
emergencetrapcumulative2<-emergencetraps %>% group_by(Pond,Date.collected) %>% mutate(Total2=replace(Total, is.na(Total), mean(Total, na.rm=TRUE)),logTotal2=log(1+Total2))

##calculate the cumulative numbers at each trap##
emergencetrapcumulative3<-emergencetrapcumulative2  %>% group_by(Pond, SS)%>% arrange(Pond, SS, Date.collected)%>% dplyr::mutate(cumemerg2=cumsum(Total2),logcumemerg2=log(1+cumemerg2))


##filter to just have the cumulative number at each trap##
emergencebysamplingstation<-emergencetrapcumulative3 %>% group_by(Pond, SS) %>% filter(Date.collected==max(Date.collected))



#### boxplot of emergence trap data###

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=10, colour = "black"))+theme(axis.text.y=element_text(size=10, colour = "black"))+theme(axis.title=element_text(size=10))+theme(plot.title=element_text(size=7) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")



emergencybypond2018<-emergencebysamplingstation %>%
  ggplot(aes(x=Sitecode, y=cumemerg2)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Pond")+
    ylab("Cumulative adults / emergence trap")+
    mytheme
    


jpeg("C:/Users/Melissa/Dropbox/Mosquito Science/Data 2011 to 2018/Github repository/Arctic_mosquito/Adultpaper/Figures/emergencybypond2018.jpeg",width = 4, height = 3,units = 'in', res = 600)
emergencybypond2018
dev.off()







```



```{r sweep totals by site 2018}

##Sweep net 2018## ##from each sweep individual##

head(sweep2018)


##First, sum up the total number caught in 6 sweeps per site per date###

sweep2018sitedate<-sweep2018 %>% group_by(SiteYear, Date) %>% summarise(Total= sum(Total), Gravid = sum(Gravid))


####then calculate the cumulative number caught per site##

sweepcumulative<-sweep2018sitedate %>% group_by(SiteYear) %>% dplyr::mutate(cumTotal=cumsum(Total),cumGravid=(Gravid))

####

##plot of total number of mosquitoes caught in sweep nets cumulatively over season##

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=10, colour = "black"))+theme(axis.text.y=element_text(size=10, colour = "black"))+theme(axis.title=element_text(size=10))+theme(plot.title=element_text(size=7) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")

 
sweep2018cumsum<-ggplot(sweepcumulative, aes(Date, cumTotal, color=SiteYear)) + geom_point(na.rm=TRUE)+ geom_line(na.rm=TRUE)+xlab("")+ylab(bquote(atop("Cumulative" , (Total / sweeps))))+mytheme

#ANOTHER WAY TO DO CUMULATIVE SUMS###

##Sum up the total number caught in each sweep rep by date###

sweep2018sitedate_2<-sweep2018 %>% group_by(Sitecode, SiteYear, Sample) %>% summarise(Total= sum(Total), Gravid = sum(Gravid))


####then standardize to the number of dates###


sweep2018sitedate_3<-sweep2018sitedate_2 %>% mutate(numdates=SiteYear)

sweep2018sitedate_3$numdates<-plyr::mapvalues(sweep2018sitedate_3$numdates, c("East2018", "Golf2018", "Ice2018", "NoOil2018", "Oil2018", "Vulgaris2018", "Vulgarissmall2018", "Waterfall2018"), c("3", "4", "4", "4", "4", "4", "4", "4"))

sweep2018sitedate_3$numdates<-as.numeric(as.character(sweep2018sitedate_3$numdates))

sweep2018sitedate_4<-sweep2018sitedate_3%>%mutate(Totaladjust=round((Total/numdates)*mean(sweep2018sitedate_3$numdates)))%>%mutate(Gravidadjust=round((Gravid/numdates)*mean(sweep2018sitedate_3$numdates)))





```


```{r C02 peak part of season clement weather}


CO2counts20172018cumsum<-CO2counts20172018subset %>%group_by(Sitecode, SiteYear)  %>%   mutate(cumsum= cumsum(Countperhour))

###subset to just the 2018 data for now, because in 2017 I didn't have all traps on at the same time in the early part of the season##

CO2counts2018cumsum<-subset(CO2counts20172018cumsum, Year=="2018")


## remove inclement weather##

CO2counts2018subset_2<-CO2counts2018cumsum%>%mutate(Weathercat=ifelse(Wspeedmps > 6.5 | TempC <8, "Inclement", "Clement"))

CO2counts2018subset_3<-subset(CO2counts2018subset_2, Weathercat=="Clement")

#filter dates in the peak part of season##
CO2counts2018subset_4<-CO2counts2018subset_3 %>% filter(Date2 >= as.Date("2017-06-15"))%>% filter(Date2 <= as.Date("2017-07-01"))




#### boxplot of C02 trap data peak season###

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=10, colour = "black"))+theme(axis.text.y=element_text(size=10, colour = "black"))+theme(axis.title=element_text(size=10))+theme(plot.title=element_text(size=7) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")



Co2sites2018<-CO2counts2018subset_4 %>%
  ggplot(aes(x=Site, y=Countperhour)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Site")+
    ylab("Count per hour in CO2 traps")+
    mytheme
    


jpeg("C:/Users/Melissa/Dropbox/Mosquito Science/Data 2011 to 2018/Github repository/Arctic_mosquito/Adultpaper/Figures/emergencybypond2018.jpeg",width = 4, height = 3,units = 'in', res = 600)
emergencybypond2018
dev.off()





```


```{r GLM  ANOVA for each life stage}

#emergencebysamplingstation2
#CO2counts2018subset_5
#sweep2018_5
#sweepgravid2018_5

nbemerg11 <- glm.nb(round(cumemerg2) ~ Sitecode, data = emergencebysamplingstation2, control=glm.control(maxit=100))
nbCo211 <- glm.nb(round(cumemerg2) ~ Sitecode, data = CO2counts2018subset_5, control=glm.control(maxit=100))
nbsweep11 <- glm.nb(round(cumemerg2) ~ Sitecode, data = sweep2018_5, control=glm.control(maxit=100))
nbsweepgravid11 <- glm.nb(round(cumemerg2) ~ Sitecode, data = sweepgravid2018_5, control=glm.control(maxit=100))

Anova(nbemerg11)
Anova(nbCo211)
Anova(nbsweep11)
Anova(nbsweepgravid11)

######Site is significant for everything except CO2##


```



```{r cumulative sums for each life stage 1 number per site}

##https://cran.r-project.org/web/packages/GlmSimulatoR/vignettes/count_data_and_overdispersion.html##

#####cumulative number in emerg traps####1 number per site###adjusted # traps###

head(emergencebysamplingstation)

##average for one trap###

 emer1trap<-emergencebysamplingstation %>%group_by(Pond) %>% dplyr::summarise(n=n(), meanemerg=mean(cumemerg2 , na.rm=TRUE), sdemerg = sd(cumemerg2 ), seemer = sdemerg/sqrt(n))

 ##total all traps##
 emerwholepond<-emergencebysamplingstation %>%group_by(Pond) %>% dplyr::summarise(n=n(), sumemerg=sum(cumemerg2 , na.rm=TRUE))%>%mutate(standemerg=(sumemerg/n)*mean(emerwholepond$n))

#####cumulative number in c02 traps ####1 number per site### ##adjusted hours in CO2traps###


###subset to just the 2018 data##

CO2counts2018subset <-subset(CO2counts20172018subset, Year=="2018")

## remove inclement weather##

CO2counts2018subset_2<-CO2counts2018subset%>%mutate(Weathercat=ifelse(Wspeedmps > 6.5 | TempC <8, "Inclement", "Clement"))

CO2counts2018subset_3<-subset(CO2counts2018subset_2, Weathercat=="Clement")

#filter dates in the peak part of season##
CO2counts2018subset_4<-CO2counts2018subset_3 %>% filter(Date2 >= as.Date("2017-06-15"))%>% filter(Date2 <= as.Date("2017-07-01"))

CO2counts2018_cumsum<-CO2counts2018subset_4 %>%group_by(SiteYear)  %>%   mutate(cumsum= cumsum(Count)) %>%   mutate(cumhours= cumsum(Hours))

CO2counts2018_cumsum_bysite<-CO2counts2018_cumsum %>% group_by(Site) %>% filter(cumhours==max(cumhours)) %>% dplyr::select(Date, Site, SiteYear, Larvhab500m, DistRus, cumsum, cumhours)%>%mutate(cumsumadjust=(cumsum/cumhours)*mean(CO2counts2018_cumsum$cumhours))



#####cumulative number in sweep nets ####1 number per site### ##adjusted to number of date sampeled ###

head(sweepcumulative)

sweepcumulative_2<-sweepcumulative %>%group_by(SiteYear) %>% filter(cumTotal==max(cumTotal))  

numdates<-c(3,4,4,4,4,4,4,4)##number of dates each site was sampeled (bc East was sampeled 3 instead of 4 times)

sweepcumulative_3<-cbind(sweepcumulative_2, numdates=numdates)

sweepcumulative_4<-sweepcumulative_3%>%mutate(cumsumTotoladjust=round((cumTotal/numdates)*mean(sweepcumulative_3$numdates)))%>%mutate(cumsumTGravidadjust=round((cumGravid/numdates)*mean(sweepcumulative_3$numdates)))

#####cumulative number gravid in sweep nets ####1 number per site### ##adjusted to number of date sampeled ###



```



```{r cumulative sums dispersion test}

##https://cran.r-project.org/web/packages/GlmSimulatoR/vignettes/count_data_and_overdispersion.html##
#https://stats.stackexchange.com/questions/10419/what-is-theta-in-a-negative-binomial-regression-fitted-with-r##
#http://biometry.github.io/APES//LectureNotes/2016-JAGS/Overdispersion/OverdispersionJAGS.html#

#####emergtraps###
emer1trap$meanemerg
emerwholepond$standemerg

####c02 traps###
CO2counts2018_cumsum_bysite$cumsumadjust

#####cumulative number in sweep nets 
sweepcumulative_4$cumsumTotoladjust

#####cumulative gravid in sweep nets 
sweepcumulative_4$cumsumTGravidadjust


###test poisson versus NB for each life stage###

## emer traps###
poisemerg <- glm(round(meanemerg) ~ 1, data = emer1trap, family = poisson)
poisemerg2 <- glm(round(standemerg) ~ 1, data = emerwholepond, family = poisson)

nbemerg <- glm.nb(round(meanemerg) ~ 1, data = emer1trap, control=glm.control(maxit=100))

rawaic<-AIC(poisemerg,nbemerg )
nR<-dim(emergtotal_3)[1]  #Sample size 
aictable(rawaic,nR) ###NB is better for emergence trap data###


## CO2###
poisCo2 <- glm(round(cumsumadjust) ~ 1, data = CO2counts2018_cumsum_bysite, family = poisson)
nbCo2 <- glm.nb(round(cumsumadjust) ~ 1, data = CO2counts2018_cumsum_bysite, control=glm.control(maxit=100))

rawaic<-AIC(poisCo2 ,nbCo2 )
nR<-dim(CO2counts2018_cumsum_bysite)[1]  #Sample size 
aictable(rawaic,nR) ###NB is better for CO2###


## Sweeps###
poissweep<- glm(cumsumTotoladjust ~ 1, data = sweepcumulative_4, family = poisson)
nbsweep <- glm.nb(cumsumTotoladjust ~ 1, data = sweepcumulative_4, control=glm.control(maxit=100))

rawaic<-AIC(poissweep ,nbsweep )
nR<-dim(sweepcumulative_4)[1]  #Sample size 
aictable(rawaic,nR) ###NB is better for sweeps###

## Sweeps Gravid ###
poissweepgravid<- glm(cumsumTGravidadjust ~ 1, data = sweepcumulative_4, family = poisson)
nbsweepgravid <- glm.nb(cumsumTGravidadjust ~ 1, data = sweepcumulative_4, control=glm.control(maxit=100))

rawaic<-AIC(poissweepgravid ,nbsweepgravid)
nR<-dim(sweepcumulative_4)[1]  #Sample size 
aictable(rawaic,nR) ###NB is better for gravids####

#####NEGATIVE BINOMIAL IS THE BEST FIT FOR ALL LIFE STAGES####


nbemerg <- glm.nb(round(meanemerg) ~ 1, data = emer1trap, control=glm.control(maxit=100))
nbCo2 <- glm.nb(cumsumadjust ~ 1, data = CO2counts2018_cumsum_bysite, control=glm.control(maxit=100))
nbsweep <- glm.nb(cumsumTotoladjust ~ 1, data = sweepcumulative_4, control=glm.control(maxit=100))
nbsweepgravid <- glm.nb(cumsumTGravidadjust ~ 1, data = sweepcumulative_4, control=glm.control(maxit=100))

###CALCULATING THE SKEW###
#https://stats.stackexchange.com/questions/10419/what-is-theta-in-a-negative-binomial-regression-fitted-with-r##


emergskew<-(1+2*(mean(emer1trap$meanemerg)/nbemerg$theta))/(sqrt(mean(emer1trap$meanemerg)*(1+(mean(emer1trap$meanemerg)/nbemerg$theta))))


Co2skew<-(1+2*(mean(CO2counts2018_cumsum_bysite$cumsumadjust)/nbCo2$theta))/(sqrt(mean(CO2counts2018_cumsum_bysite$cumsumadjust)*(1+(mean(CO2counts2018_cumsum_bysite$cumsumadjust)/nbCo2$theta))))

sweepskew<-(1+2*(mean(sweepcumulative_4$cumsumTotoladjust)/nbsweep$theta))/(sqrt(mean(sweepcumulative_4$cumsumTotoladjust)*(1+(mean(sweepcumulative_4$cumsumTotoladjust)/nbsweep$theta))))


gravidskew<-(1+2*(mean(sweepcumulative_4$cumsumTGravidadjust)/nbsweepgravid$theta))/(sqrt(mean(sweepcumulative_4$cumsumTGravidadjust)*(1+(mean(sweepcumulative_4$cumsumTGravidadjust)/nbsweepgravid$theta))))


emergskew
Co2skew
sweepskew
gravidskew

##dispersion test##NEED TO USE THE POISSON###

library(pscl)
library(DHARMa)

dispersiontest(poisemerg, trafo=2) ##trafo = 2 bc Negative binomial model assumes variance is a quadratic function of the mean.##
#dispersiontest(poisemerg2)
dispersiontest(poisCo2, trafo=2)
dispersiontest(poissweep, trafo=2)
dispersiontest(poissweepgravid, trafo=2)

####


```



```{r cumulative sums log mean to log variance plot}

#####emergtraps###
emer1trap$meanemerg
emerwholepond$standemerg

####c02 traps###
CO2counts2018_cumsum_bysite$cumsumadjust

#####cumulative number in sweep nets 
sweepcumulative_4$cumsumTotoladjust

#####cumulative gravid in sweep nets 
sweepcumulative_4$cumsumTGravidadjust

####
lifestage<-c("Emerging adults", "Host-seeking females", "Resting females", "Gravid females")

means<-c(mean(emer1trap$meanemerg), mean(CO2counts2018_cumsum_bysite$cumsumadjust), mean(sweepcumulative_4$cumsumTotoladjust), mean(sweepcumulative_4$cumsumTGravidadjust))

logmeans<-log(means)

vars<-c(var(emer1trap$meanemerg), var(CO2counts2018_cumsum_bysite$cumsumadjust), var(sweepcumulative_4$cumsumTotoladjust), var(sweepcumulative_4$cumsumTGravidadjust))

logvars<-log(vars)

meanvar<-as.data.frame(cbind(lifestage, means, vars, logmeans, logvars))

###simulate data for graph###

x<-seq(1, 25, by=2)
y1<- x
y2<- 2 * x
y3<- x^2
ypredict<-x*1.7712

simdata<-as.data.frame(cbind(x, y1, y2, y3, ypredict))

lm1<-lm(as.numeric(as.character(logvars))~as.numeric(as.character(logmeans)), data=meanvar)

######

logmeanvarplot<-ggplot(meanvar, aes(as.numeric(as.character(logmeans)), as.numeric(as.character(logvars)))) + geom_point(na.rm=TRUE)+xlab("log(Mean)")+ylab("log(Variance)")+xlim(1, 14)+ylim(1,20)+mytheme+geom_line(data=simdata, aes(x,y1),colour="blue")+geom_line(data=simdata, aes(x,ypredict),colour="black")+geom_line(data=simdata, aes(x,y2),colour="red")+ geom_text(aes(label=lifestage),hjust=-0.1, vjust=0)+ annotate(geom="text", x=12, y=6, label="y = x",color="blue")+ annotate(geom="text", x=12, y=4, label="y = 1.77x",color="black")+ annotate(geom="text", x=12, y=2, label="y = 2x",color="red")


jpeg("C:/Users/Melissa/Dropbox/Mosquito Science/Data 2011 to 2018/Github repository/Arctic_mosquito/Adultpaper/Figures/logmeanvar.jpeg",width = 4, height = 4,units = 'in', res = 600)
logmeanvarplot
dev.off()


```



```{r glms for Co2 abundance}

library(MASS)


head(CO2counts20172018subset)

CO2counts2018cumsum<-subset(CO2counts20172018cumsum, Year=="2018")

hist(CO2counts2018cumsum$Larvhab500m)
hist(CO2counts2018cumsum$Countperhour)
hist(CO2counts2018cumsum$DistRus)
hist(CO2counts2018cumsum$roughraster)

m1 <- glm.nb(round(Countperhour) ~ DaysEmerg+ Larvhab500m +DistRus+Wspeedmps+TempC+Rhperc, data = CO2counts2018cumsum)

m2 <- glm.nb(round(Countperhour) ~ poly(DaysEmerg,2)+ Larvhab500m +DistRus+Wspeedmps+TempC+Rhperc, data = CO2counts2018cumsum,control=glm.control(maxit=50))

##with topographic roughness metric##

m3 <- glm.nb(round(Countperhour) ~ poly(DaysEmerg,2)+ Larvhab500m +DistRus+roughraster+Wspeedmps+TempC+Rhperc, data = CO2counts2018cumsum,control=glm.control(maxit=50))


##with interaction effects and topo##

m4 <- glm.nb(round(Countperhour) ~ poly(DaysEmerg,2)* Larvhab500m +DistRus+roughraster+Wspeedmps+TempC+Rhperc, data = CO2counts2018cumsum,control=glm.control(maxit=50))


## is Site by itself significant?##

m5 <- glm.nb(round(Countperhour) ~ poly(DaysEmerg,2)* Site, data = CO2counts2018cumsum,control=glm.control(maxit=50))

anova(m5)

###barely, East has the fewest, but other than that, everything is similar##




```


